### ISSUE TITLE
Is the * under the <h2> tags in README necessary?

### ISSUE THREAD

**Issue by msr8** [FrenzyExists/wallpapers#4]
I wrote a script to build a readme file to preview my wallpapers (https://github.com/msr8/dotfiles). I am working on making a script for this readme too while I am at it, so I wanted to ask if the * are necessary or not

**Comment by FrenzyExists** [comment]
sup. sorry for the late message, what * are you talking about?

**Comment by msr8** [comment]
These ones
![Screenshot 2022-05-26 at 20 46 50](https://user-images.githubusercontent.com/79649185/170518643-d88f2d17-ef43-4bd1-a0a1-b9f095ca1a81.png)

**Comment by FrenzyExists** [comment]
Ah that, yeah those are for bullet points now that i remember

**Comment by FrenzyExists** [comment]
welp I have no idea where this ended so uh, gonna close it
